### PR TITLE
Added option to hide rares when killed.

### PR DESCRIPTION
**Pull request by Neophear**
Although two rares are missing their tracking-quests, and it doesn't hide on killing.

### CODE REVIEW

**Comment by Neophear** [comment]
There is a bug now. It hides killed rares no matter what option you set. I am not that confident in lua and wow to know how to fix that in a jiffy.

**Comment by seirl** [comment]
Why do you want to do this? You can loot the rares multiple times per day.

**Comment by Neophear** [comment]
You can? You don't just have one chance per day for one of the special items for each rare?

**Comment by seirl** [comment]
Yes, you can. There is no lockout.

**Comment by Neophear** [comment]
Wow my bad. I wasn't aware of that. Thanks!

**Pull request closed without merging**
